### ISSUE TITLE
Implement compliance criteria

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-program#90] opened 2023-06-22 04:04 UTC
**Description:**

We are introducing a new feature to our OpenSPP program management system: **Compliance Criteria**. This is conceptually similar to **Enrollment Criteria**, yet with operational differences.

**Requirements:**

1. **Compliance Criteria** are ongoing conditions that enrolled participants must continue to meet in order to stay active in a program and receive its benefits. Compliance checks would occur regularly at each program cycle.

2. Just like with the enrollment criteria, the compliance criteria should be flexible and customizable for each program, as different programs may have different compliance rules.

3. Technically, the compliance criteria check should be similar to that of the enrollment criteria check, but with a crucial difference: while enrollment criteria are evaluated once, compliance criteria need to be evaluated at each defined cycle or period.

**Example:**

In the 'cash for work' program, the enrollment criteria could be based on the unemployment status and income level, but the compliance criteria would look at whether the individual has worked the required number of days in a month.

**Tasks:**

1. Develop a mechanism for defining compliance criteria for each program, similar to enrollment criteria.
2. Implement regular checks for compliance at each program cycle.
3. Provide a UI to visualize the compliance or not at a given cycle for a person.

**Outcome:**

Fully functional compliance criteria feature that provides regular checks and validation against defined program rules.

The cron job will check the eligibility.  

![Image](https://github.com/OpenSPP/openspp-program/assets/2864612/ca30c770-4c54-44d8-8736-49a7cfc3acf4)

**Comment by jeremi** [comment] 2023-06-22 04:14
We need to decide if we should implement this in OpenG2P or OpenSPP

**Comment by gonzalesedwin1123** [comment] 2023-07-10 02:05
@jeremi @dasunhegoda , may I ask about the eligibility criteria. Will the "Compliance Manager" use the criteria defined in the "Eligibility Manager" to maintain consistency with the cron executed compliance criteria and the validation of eligibility available in the program and cycle buttons. 

In our current setup, beneficiaries are enrolled and their eligibility are evaluated using the criterias defined  in the "Eligibility Manager". In my understanding of the compliance criteria defined in this ticket, it will be a new manager (Compliance Manager) that will run at regular schedules (cron). Having a different criteria in the "Compliance Manager" and the "Entitlement Manager" will have an issue later on when the program users clicks the "Verify Eligibility" button in the program and cycle levels.

**Comment by nhatnm0612** [comment] 2023-07-21 05:27
# NOTE: 21/07/2023

- cron will not affect approved cycles

### NOTE: 25/07/2023

- only edit cycles that in `draft` or `to_approve` state
- not edit the cycles where `end_date` is in the past

**Comment by dasunhegoda** [comment] 2023-08-11 06:26
@gonzalesedwin1123 @nhatnm0612 : should be able to configure it when creating a program.

**Comment by nhatnm0612** [comment] 2023-08-11 06:28
> @gonzalesedwin1123 @nhatnm0612 : should be able to configure it when creating a program.

## THIS COMMENT IS OUTDATED

@dasunhegoda yes, it is configurable on program creating, and also can be set after if you change your mind

![config on program creating](https://github.com/OpenSPP/openspp-program/assets/31398072/c06b2ccd-8da8-4f10-999d-79e7656e81c0)

![change your mind? No problem](https://github.com/OpenSPP/openspp-program/assets/31398072/d4c52a69-6e9e-436a-9aeb-a080bc3edaf9)

**Comment by dasunhegoda** [comment] 2023-08-11 06:43
@nhatnm0612 : Can we move it to the eligibility tab when we are creating programs?

**Comment by nhatnm0612** [comment] 2023-08-11 06:46
> @nhatnm0612 : Can we move it to the eligibility tab when we are creating programs?

yes, it can be. Well, is it a question, or a task?

**Comment by dasunhegoda** [comment] 2023-08-11 07:11
Yes, it's better if we can move it. So it's a task. I discussed the same with @gonzalesedwin1123 too.

**Comment by celinenilla** [comment] 2023-08-21 01:38
I have discussed with Jeremi and this should be the expected behaviour:
There should be a separate tab called " Compliance". Below this tab there should be the selection to define the compliance criteria as:
- Default
- SQL-based
- Tag-based
UI for this should comply with UI from tab "Configure the Eligibility Criteria".

Eligibility should be determined as today, upon enrollment into the program. As for compliance we may want to make the triggering customisable (either when creating the cycle or when creating the entitlements). For now we will implement a button to trigger the eligibility manually only.

**Comment by dasunhegoda** [comment] 2023-08-21 02:42
Noted @celinenilla!
@nhatnm0612 : Let's make the change as above.

**Comment by nhatnm0612** [comment] 2023-08-22 16:52
> I have discussed with Jeremi and this should be the expected behaviour: There should be a separate tab called " Compliance". Below this tab there should be the selection to define the compliance criteria as:
> 
> * Default
> * SQL-based
> * Tag-based
>   UI for this should comply with UI from tab "Configure the Eligibility Criteria".
> 
> Eligibility should be determined as today, upon enrollment into the program. As for compliance we may want to make the triggering customisable (either when creating the cycle or when creating the entitlements). For now we will implement a button to trigger the eligibility manually only.

@celinenilla I found in the code to creating new cycle there is no cycle beneficiaries created, but by the `Copy Beneficiaries from Program`, so it is better to have automation triggered when create cycle beneficiaries or creating entitlements

**Comment by adriancris** [comment] 2023-10-10 02:48
This tickets needs to fixed first since it is causing an error when it is installed. To be reassigned to @gonzalesedwin1123

**Comment by adriancris** [comment] 2023-10-27 00:05
@nhatnm0612 
When using SQL Eligibility for Compliance Criteria, it does not filter out after clicking Compliance Criteria button in Cycle. Kindly check.

**Comment by adriancris** [comment] 2023-10-30 08:39
@nhatnm0612 
Cannot generate entitlements when Compliance Criteria toggle is off.

**Comment by adriancris** [comment] 2023-11-06 02:21
QA Passed. 
Working as expected.
TCs executed:
TSOS-130, 131
TSOS-153 to 159

**Closed as completed** 2023-11-08 04:12 UTC

**Comment by adriancris** [comment] 2024-02-21 12:49
tested and approved but actions were needed
